---

- name: Create a group for jenkins user
  group:
    name: '{{ slave_macos_user_group }}'
    state: present
  become: true

- name: Create jenkins user with root privileges
  user:
    name: "{{ slave_macos_jenkins_username }}"
    group: "{{ slave_macos_user_group }}"
    password: >-
      {{ slave_macos_jenkins_password | default('*************')
        | password_hash('sha512', 65534 | random(seed=inventory_hostname)
        | string) }}
    update_password: always
    state: present
    createhome: true
  become: true

- name: Set authorized key
  authorized_key:
    user: '{{ slave_macos_jenkins_username }}'
    state: present
    key: '{{ slave_macos_jenkins_public_key }}'
  become: true
  when: slave_macos_jenkins_public_key | trim

- name: Create slave home directory
  file:
    path: '{{ slave_macos_home }}'
    state: directory
    owner: '{{ slave_macos_jenkins_username }}'
    group: '{{ slave_macos_user_group }}'
    mode: 0775
  become: true
  
- import_tasks: "agent-{{ slave_agent_type }}.yml"

- import_tasks: "service-{{ slave_agent_type }}.yml"



