---

- name: Create a group for jenkins user
  group:
    name: '{{ slave_darwin_user_group }}'
    state: present
  become: true

- name: Create jenkins user with root privileges
  user:
    name: '{{ slave_darwin_jenkins_username }}'
    group: '{{ slave_darwin_user_group }}'
    password: >-
      {{ slave_darwin_jenkins_password | default('*************')
        | password_hash('sha512', 65534 | random(seed=inventory_hostname)
        | string) }}
    update_password: always
    state: present
    createhome: true
  become: true

- name: Set authorized key
  authorized_key:
    user: '{{ slave_darwin_jenkins_username }}'
    state: present
    key: '{{ slave_darwin_jenkins_public_key }}'
  become: true
  when: slave_darwin_jenkins_public_key | trim

- name: Create slave home directory
  file:
    path: '{{ slave_darwin_home }}'
    state: directory
    owner: '{{ slave_darwin_jenkins_username }}'
    group: '{{ slave_darwin_user_group }}'
    mode: 0775
  become: true

- name: Install slave jenkins agent
  jenkins_script:
    user: '{{ master_username }}'
    password: '{{ master_password }}'
    validate_certs: false
    timeout: 120
    url: '{{ master_url }}'
    script: >-
      {{ lookup('template', 'add_darwin_slave.groovy.j2') }}

