---

- name: "Download WinSW-x64.exe from https://github.com/winsw/winsw/releases/download/v2.11.0/WinSW-x64.exe"
  ansible.windows.win_get_url:
    url: 'https://github.com/winsw/winsw/releases/download/v2.11.0/WinSW-x64.exe'
    dest: '{{ slave_windows_workdir }}\jenkins-agent.exe'
    force: no

- name: Copy service file (template)
  ansible.windows.win_template:
    src: jenkins-agent.xml.j2
    dest: '{{ slave_windows_workdir }}\jenkins-agent.xml'
    
- name: Copy CA
  ansible.windows.win_copy:
    src: 'etc/ssl/certs-tinnaboo/CA/cmeetingitaCA.crt'
    dest: '{{ slave_windows_workdir }}\'
    
- name: Import CA certificate
  ansible.windows.win_shell: 'keytool.exe -importcert -file .\cmeetingitaCA.crt -cacerts -keypass changeit -storepass changeit -noprompt -alias cefrielCA'
  args:
    chdir: '{{ slave_windows_workdir }}'
  register: pv_ret
  failed_when: pv_ret.rc > 0 and pv_ret.stdout is not search("Certificate not imported, alias <cefrielCA> already exists")
    
- name: Install service
  ansible.windows.win_shell: '{{ slave_windows_workdir }}\jenkins-agent.exe install'
  args:
    chdir: '{{ slave_windows_workdir }}'
  register: pv_ret
  failed_when: pv_ret.rc > 0 and pv_ret.stdout is not search("Failed to install the service. The specified service already exists")

- name: Start the service
  win_service:
    name: '{{ slave_windows_service }}'
    state: started
    username: '{{ slave_windows_service_user }}'
    password: '{{ slave_windows_service_password | default(omit) }}'
